version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: social-media-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - social-media-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - social-media-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
  social-media-network:
    driver: bridge

volumes:
  mongodb_data:
